name: Release
on:
  pull_request:
    branches:
      - release-*
    types:
      - "closed"

jobs:
  patch:
    if: contains(github.event.pull_request.labels.*.name, 'release') && contains(github.event.pull_request.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Makefile
      run: make bump-patch
    - name: push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.JUMO_GITHUB_WRITER }}
        push-branch: 'master'
        commit-message: 'Release patch'
        force-add: 'true'
        files: VERSION
        name: commiter name
        email: my.github@email.com 

