name: Release Drafter

on:
  push:
    branches:
      - develop

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@3782ccd1a495040818a9e5d0e8bc4ed22d3b1361 #v5.12.1
        with:
          config-name: release-drafter-beta.yml
        env:
          GITHUB_TOKEN: ${{ secrets.JUMO_GITHUB_WRITER }}
